### ISSUE TITLE
Update match regexp to handle windows style paths

### ISSUE THREAD

**Issue by bucefalog** [lexay/telescope-zoxide.nvim#6]
The plugin currently does not handle Windows paths.
Updating the match regexp as follows seems to solve the issue:

local s = action_state.get_selected_entry()[1]
local path = s:match("%a:[\\/].+") or s:match("/.+") or s:match("[\\/].+")

**Comment by lexay** [comment]
Not a neovim user on Windows, lol Thanks for pointing out! Greatly appreciated!
